-- GENERATED by `lake exe x86lean-diff runs`. Do not edit by hand.
-- ⛔ A STALE FILE HERE BREAKS `Tests/Coverage.lean` AND NOTHING ELSE:
-- this executable imports `Tests.Vectors` and never `Tests.Coverage`,
-- so it can always be rebuilt to regenerate the file it invalidated.
--     lake exe x86lean-diff runs Tests/VectorRuns.lean

namespace X86.Tests

/-- The coverage-table row index of each RUN of equal mnemonics in the
differential vector table, in the vector table's own order.  A
CERTIFICATE, not a claim: `X86.Tests.vectorCoverage` checks it against
both tables and every coverage fact published about the vectors is read
off that check.  181 runs over 854 vectors and 111 rows. -/
def vectorRunIdx : List Nat :=
  [0, 1, 2, 10, 11, 10, 11, 21, 24, 25, 26, 27, 28, 34, 3, 4,
   5, 7, 8, 6, 9, 3, 4, 5, 22, 23, 29, 28, 30, 31, 32, 33,
   10, 11, 12, 17, 18, 19, 20, 17, 19, 13, 14, 15, 16, 35, 36, 37,
   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 45, 46, 47, 48, 49, 50,
   51, 52, 53, 54, 55, 56, 58, 59, 57, 58, 59, 57, 60, 61, 62, 63,
   64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
   80, 81, 82, 81, 82, 81, 82, 81, 82, 81, 82, 1, 2, 7, 8, 1,
   2, 1, 2, 0, 24, 25, 26, 27, 28, 34, 26, 27, 26, 27, 83, 0,
   1, 21, 43, 22, 23, 1, 4, 25, 24, 14, 80, 79, 83, 0, 21, 10,
   0, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 88, 84,
   85, 84, 85, 97, 98, 97, 98, 107, 108, 107, 108, 109, 110, 99, 100, 101,
   102, 103, 104, 105, 106]

end X86.Tests
