#!/usr/bin/env python3
"""hwprobe/mk_anchors.py — B0's, B1's, B2's and B3's kernel pins (D266 §6.8, D268, D271, D273), as Lean rows DERIVED from mk_rows.py.

The rows the referee runs on a processor are the rows `Tests/Anchors.lean` checks the model against,
so a pinned expectation has two origins before the kernel sees it: the SDM rule stated in mk_rows.py,
and a processor (the hwprobe job read 174/174 on an AMD EPYC 7763, D266 §5). Nothing here is typed by
hand, and nothing is read from x86lean or from x86isa.

B0 (D267) pinned 40 of the 89 non-multiply rows; B1 (D268) pins 44 of the 85 multiply rows by the same rule;
B2 (D271) pins 39 of the 110 add, sub and divide rows by it again; B3 (D273) pins 32 of the 77 cvtsd2ss rows.

⛔ ONLY THE ROWS THE DIFFERENTIAL CANNOT CARRY ARE PINNED. A row is pinned when
  X86ISA  x86isa disagrees with it, or cannot run it; the differential would then compare the model with a
          defect or with nothing
  REACH   no vector of the same form reaches the row's operand class over the 88 pre-states (for a
          comparison: the operand kinds, or the ordering; for cvtss2sd: kind, sign and a preset OE; for
          cvtsi2sd: the value class and RC; for cvttsd2si: the truncation class; for mulsd/mulss: the
          reference's path, the flags, RC, the result's sign, whether it rounded away from zero, whether
          tininess before rounding differs from after, and a preset OE, D268 §2)
The other 49 are reached by vectors that x86isa agrees with, so the differential already checks them. The
first version pinned all 89, and the A′ gate refused it (Tests.Anchors +68,196 ku against 60,901): the
section is about WHERE NO VECTOR REACHES, and 49 rows were not that.
⚠️ PINNED is DECLARED, from two measurements this generator cannot re-run in CI: the reach table over the
emitted pre-states, and `rows_on_x86isa.py`'s column (D267 §2 prints both). It fails safe: a later vector
that reaches a pinned class makes the pin redundant, never wrong. A name here that mk_rows.py does not
build is refused.

    python3 hwprobe/mk_anchors.py            print the generated block
    python3 hwprobe/mk_anchors.py --check    exit 1 unless Tests/Anchors.lean carries it byte for byte
    python3 hwprobe/mk_anchors.py --selftest the check refuses a planted row, a dropped row and a lost marker

⚠️ `--check` is TRANSPORT: it proves the Lean table is this generator's output. What makes the rows
right is mk_rows.py's rules and the processor's reading; what makes the MODEL right is the kernel.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts"))
import portable as P  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import mk_rows as M  # noqa: E402

ANCHORS = os.path.join(ROOT, "Tests", "Anchors.lean")
BEGIN = "-- ⟦B0–B4 PINS BEGIN — GENERATED by hwprobe/mk_anchors.py; change mk_rows.py and regenerate⟧"
END = "-- ⟦B0–B4 PINS END⟧"

_X = "x86isa differs"
_R = "no vector reaches"
PINNED = {
    # comparisons: COMIS at a QNaN (x86isa runs it as UCOMIS), every SNaN, a denormal beside a QNaN
    # (unreached), and equality where no vector compares a register with itself
    "comisd_qnan_one": _X, "comisd_one_qnan": _X, "comisd_qnan_den": _X,
    "comisd_snan_one": _R, "comisd_snan_den": _R,
    "ucomisd_snan_one": _R, "ucomisd_qnan_den": _R, "ucomisd_snan_den": _R, "ucomisd_one_one": _R,
    "comiss_qnan_one": _X, "comiss_one_qnan": _X, "comiss_qnan_den": _X,
    "comiss_snan_one": _R, "comiss_snan_den": _R, "comiss_one_one": _R,
    "ucomiss_snan_one": _R, "ucomiss_qnan_den": _R, "ucomiss_snan_den": _R, "ucomiss_one_one": _R,
    # min/max at an SNaN
    "minsd_snan_one": _R, "minss_snan_one": _R,
    # cvtss2sd: −0 (x86isa cannot run it, D258) and every preset OE (x86isa reads it as overflow)
    "cvtss2sd_negzero": "x86isa cannot run it",
    "cvtss2sd_one_sticky1f88": _X, "cvtss2sd_one_sticky1fbf": _X,
    "cvtss2sd_one_sticky5f88": _X, "cvtss2sd_one_sticky7f88": _X,
    "cvtss2sd_small_sticky1f88": _X, "cvtss2sd_small_sticky1fbf": _X,
    "cvtss2sd_small_sticky5f88": _X, "cvtss2sd_small_sticky7f88": _X,
    "cvtss2sd_negsmall_sticky1f88": _X, "cvtss2sd_negsmall_sticky1fbf": _X,
    "cvtss2sd_negsmall_sticky5f88": _X, "cvtss2sd_negsmall_sticky7f88": _X,
    # cvtsi2sd: integer 0 at round-down (x86isa gives −0), and two (value, RC) pairs no state reaches
    "cvtsi2sd_zero/down": _X, "cvtsi2sd_one/zero": _R, "cvtsi2sd_intmin/up": _R,
    # cvttsd2si: a binary64 SNaN, INT_MIN exactly (in range, no IE), an exact in-range result
    "cvttsd2si_snan": _R, "cvttsd2si_negtwo31": _R, "cvttsd2si_one": _R,
}
# B1 (D268): ∞ × 0 (x86isa's indefinite is positive), and what the 11 multiply vectors reach nowhere:
# an exact product without DE, a tie at nearest, a carry out of a tie, overflow at round-up, every SNaN,
# tininess before rounding that is not tininess after, an exact tiny result at three modes, and a preset OE
_MUL_X = ["mulsd_invalid", "mulss_invalid"]
_MUL_R = ["mulsd_exact/nearest", "mulsd_exact/down", "mulsd_exact/up", "mulsd_exact/zero",
          "mulsd_tiecarry/nearest", "mulsd_tiecarry/up", "mulsd_tieodd/nearest", "mulsd_negtie/nearest",
          "mulsd_overflow/up", "mulsd_negsubtie/nearest",
          "mulsd_snanqnan/nearest", "mulsd_snanqnan/down", "mulsd_snanqnan/up", "mulsd_snanqnan/zero",
          "mulsd_tinyup/nearest", "mulsd_tinyup/up", "mulsd_tinyup_swap/nearest", "mulsd_tinyup_swap/up",
          "mulsd_exacttiny/nearest", "mulsd_exacttiny/down", "mulsd_exacttiny/up", "mulsd_deeptiny/nearest",
          "mulsd_snan_den/nearest", "mulsd_snan_den/down", "mulsd_snan_den/up", "mulsd_snan_den/zero",
          "mulsd_sticky_or",
          "mulss_exact/nearest", "mulss_exact/down", "mulss_exact/up", "mulss_exact/zero",
          "mulss_tinyup/nearest", "mulss_tinyup/up", "mulss_exacttiny/down", "mulss_exacttiny/up",
          "mulss_tieodd/nearest"]
PINNED.update({"%s/%s" % (n, m): _X for n in _MUL_X for m in ("nearest", "down", "up", "zero")})
PINNED.update({n: _R for n in _MUL_R})

# B2 (D271): the indefinite's sign where x86isa's is positive (∞ − ∞, 0/0, ∞/∞), and what the 29 add, sub and
# divide vectors reach nowhere: every ∞, overflow on an add, cancellation and a zero sum at modes and signs the
# vectors miss, a carry out of a tie, divide overflow and tininess at the modes they miss, and the SNaN pairings.
# The list is b2_pin_rows.py's output over the 88 pre-states, not a hand selection.
_B2_X = ["subsd_infinf", "divsd_zero_zero", "divsd_inf_inf", "subss_infinf"]
_B2_R = [
          "addsd_tie/nearest", "subsd_sticky/nearest", "subsd_gap56/nearest", "addsd_overflow/nearest",
          "addsd_overflow/down", "addsd_overflow/up", "addsd_overflow/zero", "addsd_cancel/nearest",
          "addsd_cancel/down", "addsd_cancel/up", "addsd_cancel/zero", "addsd_zeros/down",
          "divsd_overflow/down", "divsd_overflow/up", "divsd_overflow/zero", "divsd_tiny/up",
          "divsd_tiny/zero", "addsd_negzeros", "addsd_infinf", "addsd_inf_den",
          "addsd_snan_one", "addsd_qnan_snan", "divsd_exact", "divsd_negone_zero",
          "divsd_snan_den", "divsd_inf_den", "addss_zeros/down", "addss_overflow/nearest",
          "addss_overflow/down", "addss_overflow/up", "addss_overflow/zero", "divss_tiny/nearest",
          "divss_tiny/up", "divss_tiny/zero", "addss_snan_one",
]
PINNED.update({n: _X for n in _B2_X})
PINNED.update({n: _R for n in _B2_R})

# B3 (D273): the 8 preset-OE rows (x86isa reads the sticky OE as this conversion's overflow, D272 s3), the 2 zero
# rows x86isa cannot run (D258's guard violation), and what B3's 3 vectors reach nowhere: every tie at nearest,
# rounding at down, every infinity and zero, tininess before rounding that is not tininess after, 2^-150's tie,
# the exact results and the SNaNs. The list is b3_pin_rows.py's output over the 88 pre-states, not a hand selection.
_B3_X = [
          "cvtsd2ss_one_sticky1f88", "cvtsd2ss_one_sticky1fbf", "cvtsd2ss_one_sticky5f88", "cvtsd2ss_one_sticky7f88",
          "cvtsd2ss_third_sticky1f88", "cvtsd2ss_third_sticky1fbf", "cvtsd2ss_third_sticky5f88",
          "cvtsd2ss_third_sticky7f88",
]
_B3_C = ["cvtsd2ss_zero", "cvtsd2ss_negzero"]
_B3_R = [
          "cvtsd2ss_tie/nearest", "cvtsd2ss_tie/down", "cvtsd2ss_tieodd/nearest", "cvtsd2ss_tieodd/down",
          "cvtsd2ss_sticky/down", "cvtsd2ss_third/down", "cvtsd2ss_maxtie/down", "cvtsd2ss_tinyinexact/up",
          "cvtsd2ss_tinyafter/nearest", "cvtsd2ss_tinyafter/up", "cvtsd2ss_halfmin/nearest", "cvtsd2ss_negden/zero",
          "cvtsd2ss_one", "cvtsd2ss_inf", "cvtsd2ss_neginf", "cvtsd2ss_qnan", "cvtsd2ss_snan",
          "cvtsd2ss_snan_payload", "cvtsd2ss_max", "cvtsd2ss_minnorm", "cvtsd2ss_minsub", "cvtsd2ss_exacttiny",
]
PINNED.update({n: _X for n in _B3_X})
PINNED.update({n: "x86isa cannot run it" for n in _B3_C})
PINNED.update({n: _R for n in _B3_R})

# B4 (P2 batch 45): the three integer conversions that ROUND -- cvtsi2ss from int32 and int64, and cvtsi2sdq.
# x86isa differs on the three zero rows at round-down, where it reads +0 for a -0 result (D274 s1). The rest is what
# B4's 6 vectors reach nowhere across the 88 pre-states: every tie and sticky case at the modes the vectors miss, the
# exact and width rows, and the preset-flag rows. The list is hwprobe/reach_table.py's output -- a COMMAND, re-runnable,
# not a scratch pass and not a hand selection: `python3 hwprobe/reach_table.py` prints TOTAL 127 / PINNED 85 / CARRIED 42.
_B4_X = [
          "cvtsi2ss_zero/down", "cvtsi2ssq_zero/down", "cvtsi2sdq_zero/down",
]
_B4_R = [
          "cvtsi2ss_tie/nearest", "cvtsi2ss_tie/down", "cvtsi2ss_tie/up", "cvtsi2ss_tie/zero",
          "cvtsi2ss_tieodd/nearest", "cvtsi2ss_tieodd/down", "cvtsi2ss_tieodd/up", "cvtsi2ss_tieodd/zero",
          "cvtsi2ss_sticky/nearest", "cvtsi2ss_sticky/down", "cvtsi2ss_sticky/up", "cvtsi2ss_sticky/zero",
          "cvtsi2ss_above/nearest", "cvtsi2ss_above/down", "cvtsi2ss_above/up", "cvtsi2ss_above/zero",
          "cvtsi2ss_negtie/nearest", "cvtsi2ss_negtie/down", "cvtsi2ss_negtie/up", "cvtsi2ss_negtie/zero",
          "cvtsi2ss_negsticky/nearest", "cvtsi2ss_negsticky/down", "cvtsi2ss_negsticky/up",
          "cvtsi2ss_negsticky/zero", "cvtsi2ss_max/down", "cvtsi2ss_exact", "cvtsi2ss_one_sticky7f88",
          "cvtsi2ss_tie_sticky1f88", "cvtsi2ss_tie_sticky1fbf", "cvtsi2ss_tie_sticky5f88",
          "cvtsi2ss_tie_sticky7f88", "cvtsi2ssq_tie/nearest", "cvtsi2ssq_tie/down", "cvtsi2ssq_tie/up",
          "cvtsi2ssq_tie/zero", "cvtsi2ssq_sticky/nearest", "cvtsi2ssq_sticky/down", "cvtsi2ssq_sticky/up",
          "cvtsi2ssq_sticky/zero", "cvtsi2ssq_negtie/nearest", "cvtsi2ssq_negtie/down", "cvtsi2ssq_negtie/up",
          "cvtsi2ssq_negtie/zero", "cvtsi2ssq_negsticky/nearest", "cvtsi2ssq_negsticky/down",
          "cvtsi2ssq_negsticky/up", "cvtsi2ssq_negsticky/zero", "cvtsi2ssq_max/down", "cvtsi2ssq_width/zero",
          "cvtsi2ssq_exact", "cvtsi2ssq_one_sticky7f88", "cvtsi2ssq_tie_sticky1f88", "cvtsi2ssq_tie_sticky1fbf",
          "cvtsi2ssq_tie_sticky5f88", "cvtsi2ssq_tie_sticky7f88", "cvtsi2sdq_tie/nearest", "cvtsi2sdq_tie/down",
          "cvtsi2sdq_tie/up", "cvtsi2sdq_tie/zero", "cvtsi2sdq_tieodd/nearest", "cvtsi2sdq_tieodd/down",
          "cvtsi2sdq_tieodd/up", "cvtsi2sdq_tieodd/zero", "cvtsi2sdq_sticky/nearest", "cvtsi2sdq_sticky/down",
          "cvtsi2sdq_sticky/up", "cvtsi2sdq_sticky/zero", "cvtsi2sdq_negtie/nearest", "cvtsi2sdq_negtie/down",
          "cvtsi2sdq_negtie/up", "cvtsi2sdq_negtie/zero", "cvtsi2sdq_negsticky/nearest", "cvtsi2sdq_negsticky/down",
          "cvtsi2sdq_negsticky/up", "cvtsi2sdq_negsticky/zero", "cvtsi2sdq_max/down", "cvtsi2sdq_exact",
          "cvtsi2sdq_one_sticky7f88", "cvtsi2sdq_tie_sticky1f88", "cvtsi2sdq_tie_sticky1fbf",
          "cvtsi2sdq_tie_sticky5f88", "cvtsi2sdq_tie_sticky7f88",
]
PINNED.update({n: _X for n in _B4_X})
PINNED.update({n: _R for n in _B4_R})

# B4's hardware reading lands before its batch, as B3's did (D272): its rows are PENDING until the batch names its
# pins, so the tracked block stays byte-identical. B3 (D273) retired the set its own rows sat in.
# B6a (D290): CVTS?2SI. x86isa agrees with every row (D287 s4), so the pins are hwprobe/cvt2si_reach.py's output: the
# rows whose ROUNDING PATH (nan, inf, zero, exact, toward, away, tie, range) with its sign, and RC where inexact, no
# vector of the same form presents over the 88 pre-states. Every tie and every away-at-nearest is here (D289 s2).
_B6A_R = [
          "cvtsd2si_tie/nearest", "cvtsd2si_tie/down", "cvtsd2si_tie/up", "cvtsd2si_tie/zero",
          "cvtsd2si_tieodd/nearest", "cvtsd2si_tieodd/down", "cvtsd2si_tieodd/up", "cvtsd2si_tieodd/zero",
          "cvtsd2si_negtie/nearest", "cvtsd2si_negtie/down", "cvtsd2si_negtie/up", "cvtsd2si_negtie/zero",
          "cvtsd2si_negfrac/nearest", "cvtsd2si_half/nearest", "cvtsd2si_half/down", "cvtsd2si_half/up",
          "cvtsd2si_half/zero", "cvtsd2si_neghalf/nearest", "cvtsd2si_neghalf/down", "cvtsd2si_neghalf/up",
          "cvtsd2si_neghalf/zero", "cvtsd2si_top/down", "cvtsd2si_top/zero", "cvtsd2si_bottom/nearest",
          "cvtsd2si_bottom/up", "cvtsd2si_bottom/zero", "cvtsd2si_exact", "cvtsd2si_negexact", "cvtsd2si_inf",
          "cvtsd2si_neginf", "cvtsd2si_negtwo31", "cvtsd2si_exact_sticky1f88", "cvtsd2si_exact_sticky1fbf",
          "cvtsd2si_exact_sticky5f88", "cvtsd2si_exact_sticky7f88", "cvtsd2siq_tie/nearest", "cvtsd2siq_tie/down",
          "cvtsd2siq_tie/up", "cvtsd2siq_tie/zero", "cvtsd2siq_tieodd/nearest", "cvtsd2siq_tieodd/down",
          "cvtsd2siq_tieodd/up", "cvtsd2siq_tieodd/zero", "cvtsd2siq_negtie/nearest", "cvtsd2siq_negtie/down",
          "cvtsd2siq_negtie/up", "cvtsd2siq_negtie/zero", "cvtsd2siq_negfrac/nearest", "cvtsd2siq_half/nearest",
          "cvtsd2siq_half/down", "cvtsd2siq_half/up", "cvtsd2siq_half/zero", "cvtsd2siq_neghalf/nearest",
          "cvtsd2siq_neghalf/down", "cvtsd2siq_neghalf/up", "cvtsd2siq_neghalf/zero", "cvtsd2siq_top/nearest",
          "cvtsd2siq_top/down", "cvtsd2siq_top/up", "cvtsd2siq_top/zero", "cvtsd2siq_bottom/nearest",
          "cvtsd2siq_bottom/down", "cvtsd2siq_bottom/up", "cvtsd2siq_bottom/zero", "cvtsd2siq_exact",
          "cvtsd2siq_negexact", "cvtsd2siq_inf", "cvtsd2siq_neginf", "cvtsd2siq_two31", "cvtsd2siq_negtwo31",
          "cvtsd2siq_big", "cvtsd2siq_negtwo63", "cvtsd2siq_exact_sticky1f88", "cvtsd2siq_exact_sticky1fbf",
          "cvtsd2siq_exact_sticky5f88", "cvtsd2siq_exact_sticky7f88", "cvtss2si_tie/nearest", "cvtss2si_tie/down",
          "cvtss2si_tie/up", "cvtss2si_tie/zero", "cvtss2si_tieodd/nearest", "cvtss2si_tieodd/down",
          "cvtss2si_tieodd/up", "cvtss2si_tieodd/zero", "cvtss2si_negtie/nearest", "cvtss2si_negtie/down",
          "cvtss2si_negtie/up", "cvtss2si_negtie/zero", "cvtss2si_negfrac/nearest", "cvtss2si_half/nearest",
          "cvtss2si_half/down", "cvtss2si_half/up", "cvtss2si_half/zero", "cvtss2si_neghalf/nearest",
          "cvtss2si_neghalf/down", "cvtss2si_neghalf/up", "cvtss2si_neghalf/zero", "cvtss2si_bottom/nearest",
          "cvtss2si_bottom/down", "cvtss2si_bottom/up", "cvtss2si_bottom/zero", "cvtss2si_negexact", "cvtss2si_inf",
          "cvtss2si_neginf", "cvtss2si_negtwo31", "cvtss2siq_tie/nearest", "cvtss2siq_tie/down", "cvtss2siq_tie/up",
          "cvtss2siq_tie/zero", "cvtss2siq_tieodd/nearest", "cvtss2siq_tieodd/down", "cvtss2siq_tieodd/up",
          "cvtss2siq_tieodd/zero", "cvtss2siq_negtie/nearest", "cvtss2siq_negtie/down", "cvtss2siq_negtie/up",
          "cvtss2siq_negtie/zero", "cvtss2siq_negfrac/nearest", "cvtss2siq_half/nearest", "cvtss2siq_half/down",
          "cvtss2siq_half/up", "cvtss2siq_half/zero", "cvtss2siq_neghalf/nearest", "cvtss2siq_neghalf/down",
          "cvtss2siq_neghalf/up", "cvtss2siq_neghalf/zero", "cvtss2siq_inf", "cvtss2siq_neginf", "cvtss2siq_two63",
          "cvtss2siq_max",
]
PINNED.update({n: _R for n in _B6A_R})

# B6b (D293): SQRTS?. x86isa differs on the 6 negative sources (its indefinite has no sign bit, D287 s4); the rest is
# hwprobe/sqrt_reach.py's output, the rows whose PATH (with a denormal source, RC where inexact, and a preset flag) no
# vector of the same format presents over the 88 pre-states.
_B6B_X = ["sqrtsd_negden", "sqrtsd_neginf", "sqrtsd_negone", "sqrtss_negden", "sqrtss_neginf", "sqrtss_negone"]
_B6B_R = [
          "sqrtsd_four", "sqrtsd_one", "sqrtsd_quarter", "sqrtsd_inf", "sqrtsd_snan", "sqrtsd_four_sticky1f88",
          "sqrtsd_four_sticky1fbf", "sqrtsd_four_sticky5f88", "sqrtsd_four_sticky7f88", "sqrtss_four", "sqrtss_one",
          "sqrtss_quarter", "sqrtss_inf", "sqrtss_snan", "sqrtss_four_sticky1f88", "sqrtss_four_sticky1fbf",
          "sqrtss_four_sticky5f88", "sqrtss_four_sticky7f88",
]
PINNED.update({n: _X for n in _B6B_X})
PINNED.update({n: _R for n in _B6B_R})

PENDING: set[str] = set()   # B6b named its pins in D293; nothing is pending.

# B5 (D285): the packed arithmetic. Its reach is LANE-LEVEL (hwprobe/packed_reach.py, D285 s1), because a 128-bit
# source equal to a row's is reached by no state and the literal rule would pin all 92. x86isa differs on the 8
# top-lane indefinites (D284); the rest is packed_reach.py's output over the 88 pre-states, not a hand selection.
_B5_X = ["%s_indef@%d" % (m, 3 if m.endswith("ps") else 1)
         for m in ("mulps", "mulpd", "addps", "addpd", "subps", "subpd", "divps", "divpd")]
_B5_R = [
          "mulpd_loud@0", "mulpd_loud@1", "addps_mix/nearest", "addps_mix/down", "addps_mix/up", "addps_mix/zero",
          "divps_mix/nearest", "divps_loud@0", "divps_loud@1", "divps_loud@2", "divps_loud@3", "divps_de_split",
          "divps_ze_de", "divps_ze_only",
          "addpd_mix/nearest", "addpd_mix/down", "addpd_mix/up", "addpd_mix/zero", "addpd_loud@0", "addpd_loud@1",
          "subps_mix/nearest", "subps_mix/down", "subps_mix/up", "subps_mix/zero", "subpd_mix/nearest",
          "subpd_mix/down", "subpd_mix/up", "subpd_mix/zero", "subpd_loud@0", "subpd_loud@1", "divpd_loud@0",
          "divpd_loud@1",
]
# ⚖️ PINNED IN TWO STEPS, BY PRICE (D285 s3): all 40 at once was ~137k ku on Tests.Anchors against A′'s ~122.9k.
# Step A pinned the 8 x86isa rows and the reach rows of mulps, mulpd, addps and divps; step B (D286) pinned the rest.
_B5_R_NEXT: list[str] = [
]
# B7 (D294): SQRTPS and CVTPD2PS, read before their batch; pending until it names its pins.
PPENDING: set[str] = {"p_sqrtps", "p_cvtpd2ps"}
PPINNED = {n: _X for n in _B5_X}
PPINNED.update({n: _R for n in _B5_R})

COMIS = {"p_comisd": ("true", ".q"), "p_ucomisd": ("false", ".q"),
         "p_comiss": ("true", ".d"), "p_ucomiss": ("false", ".d")}


def rows():
    M.ROWS.clear()
    M.build()
    built = {r[0] for r in M.ROWS}
    missing = sorted(set(PINNED) - built)
    if missing:
        raise SystemExit("mk_anchors: PINNED names rows mk_rows.py does not build: %s" % missing)
    return list(M.ROWS)


def prows():
    M.PROWS.clear()
    M.build_packed()
    built = {r[0] for r in M.PROWS}
    missing = sorted((set(PPINNED) | set(_B5_R_NEXT)) - built)
    if set(PPINNED) & set(_B5_R_NEXT):
        raise SystemExit("mk_anchors: a row is both pinned and held for the next step: %s"
                         % sorted(set(PPINNED) & set(_B5_R_NEXT)))
    if missing:
        raise SystemExit("mk_anchors: PPINNED names rows mk_rows.py does not build: %s" % missing)
    return list(M.PROWS)


def hx(v, digits):
    return "0x%0*x" % (digits, v)


# (theorem, which hwprobe rows, the tuple type, how a row prints, the per-row check)
FAMILIES = [
    ("b0_comis_pins", lambda fn: fn in COMIS,
     "Bool × Size × BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (COMIS[fn][0], COMIS[fn][1], hx(mx, 4), hx(a, 16), hx(b, 16),
                                           hx(want, 3), hx(fl, 2)),
     ["(fun (o, sz, mx, a, b, e, fl) =>",
      "  let t := step ⟨.vcomis o sz .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl (b0Rflags t.flags &&& 0x8d5) e)"]),
    ("b0_minmax_pins", lambda fn: fn in ("p_minsd", "p_minss"),
     "Size × BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (".q" if fn == "p_minsd" else ".d", hx(mx, 4), hx(a, 16),
                                           hx(b, 16), hx(want, 16), hx(mask, 16), hx(fl, 2)),
     ["(fun (sz, mx, a, b, r, m, fl) =>",
      "  let t := step ⟨.vminmax false sz .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& m) r)"]),
    ("b0_cvtss2sd_pins", lambda fn: fn == "p_cvtss2sd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtss2sd .x1 .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b0_cvtsi2sd_pins", lambda fn: fn == "p_cvtsi2sd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtsi2 true false .x0 .rdi, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b0_cvttsd2si_pins", lambda fn: fn == "p_cvttsd2si",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtt2si true false .rax .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl (t.regs.rax &&& 0xffffffff) r)"]),
    ("b1_mulsd_pins", lambda fn: fn == "p_mulsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .mul .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b1_mulss_pins", lambda fn: fn == "p_mulss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .mul .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_addsd_pins", lambda fn: fn == "p_addsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .add .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_subsd_pins", lambda fn: fn == "p_subsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .sub .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_divsd_pins", lambda fn: fn == "p_divsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .div .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_addss_pins", lambda fn: fn == "p_addss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .add .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_subss_pins", lambda fn: fn == "p_subss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .sub .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_divss_pins", lambda fn: fn == "p_divss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .div .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    # B3: the probe's own shape, `cvtsd2ss %xmm0, %xmm1` with a canary in xmm1's bits 63:32, all 64 bits checked
    ("b4_cvtsi2ss_pins", lambda fn: fn == "p_cvtsi2ss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vcvtsi2 false false .x1 .rdi, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b4_cvtsi2ssq_pins", lambda fn: fn == "p_cvtsi2ssq",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vcvtsi2 false true .x1 .rdi, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b4_cvtsi2sdq_pins", lambda fn: fn == "p_cvtsi2sdq",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vcvtsi2 true true .x1 .rdi, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b6a_cvtsd2si_pins", lambda fn: fn == "p_cvtsd2si",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvt2si true false .rax .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl t.regs.rax r)"]),
    ("b6a_cvtsd2siq_pins", lambda fn: fn == "p_cvtsd2siq",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvt2si true true .rax .x0, 5⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl t.regs.rax r)"]),
    ("b6a_cvtss2si_pins", lambda fn: fn == "p_cvtss2si",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvt2si false false .rax .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl t.regs.rax r)"]),
    ("b6a_cvtss2siq_pins", lambda fn: fn == "p_cvtss2siq",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvt2si false true .rax .x0, 5⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl t.regs.rax r)"]),
    ("b6b_sqrtsd_pins", lambda fn: fn == "p_sqrtsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vsqrt .q .x1 .x0, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b6b_sqrtss_pins", lambda fn: fn == "p_sqrtss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vsqrt .d .x1 .x0, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b3_cvtsd2ss_pins", lambda fn: fn == "p_cvtsd2ss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vcvtsd2ss .x1 .x0, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
]


# B5: the probe's own shape, `<op>p? %xmm1, %xmm0` over all 128 bits of both, every bit of %xmm0 checked
_PBYTES = {"ps": ("false", 3), "pd": ("true", 4)}
PFAMILIES = [
    ("b5_%s%s_pins" % (op, suf), "p_%s%s" % (op, suf),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vparith .%s %s .x0 .x1, %d⟩ (b5Pre mx a b)" % ((op,) + _PBYTES[suf]),
      "  b5Agrees t mx fl (t.getXmm .x0) r)"])
    for op in ("mul", "add", "sub", "div") for suf in ("ps", "pd")
]
# The families whose `decide` needs more than the elaborator's default recursion depth, and how much.
RECDEPTH = {"b6b_sqrtsd_pins": 8000, "b6b_sqrtss_pins": 8000}
PTY = "BitVec 32 × BitVec 128 × BitVec 128 × BitVec 128 × BitVec 32"


def block():
    rs = rows()
    lines = [BEGIN]
    used = 0
    for thm, pick, ty, fmt, check in FAMILIES:
        allf = [r for r in rs if pick(r[1])]
        used += len(allf)
        fam = [r for r in allf if r[0] in PINNED]
        lines += [""] + (["-- `isqrtGo` recurses once per root bit, past the elaborator's default depth (D293).",
                          "set_option maxRecDepth %d in" % RECDEPTH[thm]] if thm in RECDEPTH else [])
        lines += ["theorem %s :" % thm, "  ([  -- %d of hwprobe's %d rows" % (len(fam), len(allf))]
        for i, (n, fn, mx, a, b, want, mask, fl) in enumerate(fam):
            sep = "," if i + 1 < len(fam) else ""
            lines.append("    (%s)%s  -- %s · %s" % (", ".join(fmt(fn, mx, a, b, want, mask, fl)), sep, n,
                                                   PINNED[n]))
        lines.append("  ] : List (%s)).all" % ty)
        lines += ["    " + c for c in check]
        lines[-1] += " = true := by decide"
    pending = sum(1 for r in rs if r[1] in PENDING)
    if used + pending != len(rs):
        raise SystemExit("mk_anchors: %d of mk_rows.py's rows are in no family and not pending"
                         % (len(rs) - used - pending))
    prs = prows()
    pused = 0
    for thm, fname, check in PFAMILIES:
        allf = [r for r in prs if r[1] == fname]
        pused += len(allf)
        fam = [r for r in allf if r[0] in PPINNED]
        if not fam:
            continue
        lines += ["", "theorem %s :" % thm, "  ([  -- %d of hwprobe's %d rows" % (len(fam), len(allf))]
        for i, (n, fn, mx, A, B, want, f) in enumerate(fam):
            sep = "," if i + 1 < len(fam) else ""
            lines.append("    (%s, %s, %s, %s, %s)%s  -- %s · %s" % (hx(mx, 4), hx(A, 32), hx(B, 32), hx(want, 32),
                                                                 hx(f, 2), sep, n, PPINNED[n]))
        lines.append("  ] : List (%s)).all" % PTY)
        lines += ["    " + c for c in check]
        lines[-1] += " = true := by decide"
    ppend = sum(1 for r in prs if r[1] in PPENDING)
    if pused + ppend != len(prs):
        raise SystemExit("mk_anchors: %d of mk_rows.py's packed rows are in no family and not pending"
                         % (len(prs) - pused - ppend))
    lines += ["", END]
    return lines


def extract(text):
    """The tracked block, or None when either marker is missing."""
    ls = text.split("\n")
    if BEGIN not in ls or END not in ls:
        return None
    i, j = ls.index(BEGIN), ls.index(END)
    return ls[i:j + 1] if i < j else None


def compare(text, want):
    got = extract(text)
    if got is None:
        return ["the generated block's markers are missing from Tests/Anchors.lean"]
    if got == want:
        return []
    bad = [k for k in range(max(len(got), len(want)))
           if k >= len(got) or k >= len(want) or got[k] != want[k]]
    return ["%d line(s) differ from the generator, first at block line %d" % (len(bad), bad[0])]


def selftest():
    want = block()
    text = open(ANCHORS, encoding="utf-8").read()
    row = next(l for l in want if "cvtsi2sd_zero/down " in l)
    arms = [
        ("control: the tracked block is the generator's output", not compare(text, want)),
        ("a row's expected value is changed",
         bool(compare(text.replace(row, row.replace(", 0x0000000000000000, 0x00)", ", 0x8000000000000000, 0x00)")), want))),
        ("a row is dropped", bool(compare(text.replace(row + "\n", ""), want))),
        ("the END marker is lost", bool(compare(text.replace(END, "  --"), want))),
    ]
    ok = True
    for name, good in arms:
        print(("  ✔ " if good else "  ✖ ") + name)
        ok = ok and good
    print("✅ mk_anchors selftest" if ok else "⛔ mk_anchors selftest FAILED")
    return 0 if ok else 1


def main(argv):
    # ⛔ THIS CARRIED A HAND-ROLLED COPY of portable.strict_flags (reject any `--flag`, exit 2).
    # The behaviour was RIGHT — measured rc 2 — but a duplicate is invisible to
    # `check_flag_strictness`, which recognises `strict_flags` and `argparse` and nothing else, so
    # this file read as UNPROTECTED to the one gate that asks the question. A shared helper
    # declining your case is a reason to widen the factoring; one that already fits is a reason to
    # stop copying it. rc moves 2 -> 1; nothing reads it (CI and preflight use --check/--selftest).
    P.strict_flags(__file__, argv)
    if "--selftest" in argv:
        return selftest()
    if "--check" in argv:
        bad = compare(open(ANCHORS, encoding="utf-8").read(), block())
        for b in bad:
            print("⛔ " + b)
        if not bad:
            print("✅ Tests/Anchors.lean carries mk_anchors.py's block byte for byte (%d lines)" % len(block()))
        return 1 if bad else 0
    print("\n".join(block()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
