#!/usr/bin/env python3
"""hwprobe/mk_anchors.py — B0's, B1's, B2's and B3's kernel pins (D266 §6.8, D268, D271, D273), as Lean rows DERIVED from mk_rows.py.

The rows the referee runs on a processor are the rows `Tests/Anchors.lean` checks the model against,
so a pinned expectation has two origins before the kernel sees it: the SDM rule stated in mk_rows.py,
and a processor (the hwprobe job read 174/174 on an AMD EPYC 7763, D266 §5). Nothing here is typed by
hand, and nothing is read from x86lean or from x86isa.

B0 (D267) pinned 40 of the 89 non-multiply rows; B1 (D268) pins 44 of the 85 multiply rows by the same rule;
B2 (D271) pins 39 of the 110 add, sub and divide rows by it again; B3 (D273) pins 32 of the 77 cvtsd2ss rows.

⛔ ONLY THE ROWS THE DIFFERENTIAL CANNOT CARRY ARE PINNED. A row is pinned when
  X86ISA  x86isa disagrees with it, or cannot run it; the differential would then compare the model with a
          defect or with nothing
  REACH   no vector of the same form reaches the row's operand class over the 88 pre-states (for a
          comparison: the operand kinds, or the ordering; for cvtss2sd: kind, sign and a preset OE; for
          cvtsi2sd: the value class and RC; for cvttsd2si: the truncation class; for mulsd/mulss: the
          reference's path, the flags, RC, the result's sign, whether it rounded away from zero, whether
          tininess before rounding differs from after, and a preset OE, D268 §2)
The other 49 are reached by vectors that x86isa agrees with, so the differential already checks them. The
first version pinned all 89, and the A′ gate refused it (Tests.Anchors +68,196 ku against 60,901): the
section is about WHERE NO VECTOR REACHES, and 49 rows were not that.
⚠️ PINNED is DECLARED, from two measurements this generator cannot re-run in CI: the reach table over the
emitted pre-states, and `rows_on_x86isa.py`'s column (D267 §2 prints both). It fails safe: a later vector
that reaches a pinned class makes the pin redundant, never wrong. A name here that mk_rows.py does not
build is refused.

    python3 hwprobe/mk_anchors.py            print the generated block
    python3 hwprobe/mk_anchors.py --check    exit 1 unless Tests/Anchors.lean carries it byte for byte
    python3 hwprobe/mk_anchors.py --selftest the check refuses a planted row, a dropped row and a lost marker

⚠️ `--check` is TRANSPORT: it proves the Lean table is this generator's output. What makes the rows
right is mk_rows.py's rules and the processor's reading; what makes the MODEL right is the kernel.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import mk_rows as M  # noqa: E402

ANCHORS = os.path.join(ROOT, "Tests", "Anchors.lean")
BEGIN = "-- ⟦B0–B3 PINS BEGIN — GENERATED by hwprobe/mk_anchors.py; change mk_rows.py and regenerate⟧"
END = "-- ⟦B0–B3 PINS END⟧"

_X = "x86isa differs"
_R = "no vector reaches"
PINNED = {
    # comparisons: COMIS at a QNaN (x86isa runs it as UCOMIS), every SNaN, a denormal beside a QNaN
    # (unreached), and equality where no vector compares a register with itself
    "comisd_qnan_one": _X, "comisd_one_qnan": _X, "comisd_qnan_den": _X,
    "comisd_snan_one": _R, "comisd_snan_den": _R,
    "ucomisd_snan_one": _R, "ucomisd_qnan_den": _R, "ucomisd_snan_den": _R, "ucomisd_one_one": _R,
    "comiss_qnan_one": _X, "comiss_one_qnan": _X, "comiss_qnan_den": _X,
    "comiss_snan_one": _R, "comiss_snan_den": _R, "comiss_one_one": _R,
    "ucomiss_snan_one": _R, "ucomiss_qnan_den": _R, "ucomiss_snan_den": _R, "ucomiss_one_one": _R,
    # min/max at an SNaN
    "minsd_snan_one": _R, "minss_snan_one": _R,
    # cvtss2sd: −0 (x86isa cannot run it, D258) and every preset OE (x86isa reads it as overflow)
    "cvtss2sd_negzero": "x86isa cannot run it",
    "cvtss2sd_one_sticky1f88": _X, "cvtss2sd_one_sticky1fbf": _X,
    "cvtss2sd_one_sticky5f88": _X, "cvtss2sd_one_sticky7f88": _X,
    "cvtss2sd_small_sticky1f88": _X, "cvtss2sd_small_sticky1fbf": _X,
    "cvtss2sd_small_sticky5f88": _X, "cvtss2sd_small_sticky7f88": _X,
    "cvtss2sd_negsmall_sticky1f88": _X, "cvtss2sd_negsmall_sticky1fbf": _X,
    "cvtss2sd_negsmall_sticky5f88": _X, "cvtss2sd_negsmall_sticky7f88": _X,
    # cvtsi2sd: integer 0 at round-down (x86isa gives −0), and two (value, RC) pairs no state reaches
    "cvtsi2sd_zero/down": _X, "cvtsi2sd_one/zero": _R, "cvtsi2sd_intmin/up": _R,
    # cvttsd2si: a binary64 SNaN, INT_MIN exactly (in range, no IE), an exact in-range result
    "cvttsd2si_snan": _R, "cvttsd2si_negtwo31": _R, "cvttsd2si_one": _R,
}
# B1 (D268): ∞ × 0 (x86isa's indefinite is positive), and what the 11 multiply vectors reach nowhere:
# an exact product without DE, a tie at nearest, a carry out of a tie, overflow at round-up, every SNaN,
# tininess before rounding that is not tininess after, an exact tiny result at three modes, and a preset OE
_MUL_X = ["mulsd_invalid", "mulss_invalid"]
_MUL_R = ["mulsd_exact/nearest", "mulsd_exact/down", "mulsd_exact/up", "mulsd_exact/zero",
          "mulsd_tiecarry/nearest", "mulsd_tiecarry/up", "mulsd_tieodd/nearest", "mulsd_negtie/nearest",
          "mulsd_overflow/up", "mulsd_negsubtie/nearest",
          "mulsd_snanqnan/nearest", "mulsd_snanqnan/down", "mulsd_snanqnan/up", "mulsd_snanqnan/zero",
          "mulsd_tinyup/nearest", "mulsd_tinyup/up", "mulsd_tinyup_swap/nearest", "mulsd_tinyup_swap/up",
          "mulsd_exacttiny/nearest", "mulsd_exacttiny/down", "mulsd_exacttiny/up", "mulsd_deeptiny/nearest",
          "mulsd_snan_den/nearest", "mulsd_snan_den/down", "mulsd_snan_den/up", "mulsd_snan_den/zero",
          "mulsd_sticky_or",
          "mulss_exact/nearest", "mulss_exact/down", "mulss_exact/up", "mulss_exact/zero",
          "mulss_tinyup/nearest", "mulss_tinyup/up", "mulss_exacttiny/down", "mulss_exacttiny/up",
          "mulss_tieodd/nearest"]
PINNED.update({"%s/%s" % (n, m): _X for n in _MUL_X for m in ("nearest", "down", "up", "zero")})
PINNED.update({n: _R for n in _MUL_R})

# B2 (D271): the indefinite's sign where x86isa's is positive (∞ − ∞, 0/0, ∞/∞), and what the 29 add, sub and
# divide vectors reach nowhere: every ∞, overflow on an add, cancellation and a zero sum at modes and signs the
# vectors miss, a carry out of a tie, divide overflow and tininess at the modes they miss, and the SNaN pairings.
# The list is b2_pin_rows.py's output over the 88 pre-states, not a hand selection.
_B2_X = ["subsd_infinf", "divsd_zero_zero", "divsd_inf_inf", "subss_infinf"]
_B2_R = [
          "addsd_tie/nearest", "subsd_sticky/nearest", "subsd_gap56/nearest", "addsd_overflow/nearest",
          "addsd_overflow/down", "addsd_overflow/up", "addsd_overflow/zero", "addsd_cancel/nearest",
          "addsd_cancel/down", "addsd_cancel/up", "addsd_cancel/zero", "addsd_zeros/down",
          "divsd_overflow/down", "divsd_overflow/up", "divsd_overflow/zero", "divsd_tiny/up",
          "divsd_tiny/zero", "addsd_negzeros", "addsd_infinf", "addsd_inf_den",
          "addsd_snan_one", "addsd_qnan_snan", "divsd_exact", "divsd_negone_zero",
          "divsd_snan_den", "divsd_inf_den", "addss_zeros/down", "addss_overflow/nearest",
          "addss_overflow/down", "addss_overflow/up", "addss_overflow/zero", "divss_tiny/nearest",
          "divss_tiny/up", "divss_tiny/zero", "addss_snan_one",
]
PINNED.update({n: _X for n in _B2_X})
PINNED.update({n: _R for n in _B2_R})

# B3 (D273): the 8 preset-OE rows (x86isa reads the sticky OE as this conversion's overflow, D272 s3), the 2 zero
# rows x86isa cannot run (D258's guard violation), and what B3's 3 vectors reach nowhere: every tie at nearest,
# rounding at down, every infinity and zero, tininess before rounding that is not tininess after, 2^-150's tie,
# the exact results and the SNaNs. The list is b3_pin_rows.py's output over the 88 pre-states, not a hand selection.
_B3_X = [
          "cvtsd2ss_one_sticky1f88", "cvtsd2ss_one_sticky1fbf", "cvtsd2ss_one_sticky5f88", "cvtsd2ss_one_sticky7f88",
          "cvtsd2ss_third_sticky1f88", "cvtsd2ss_third_sticky1fbf", "cvtsd2ss_third_sticky5f88",
          "cvtsd2ss_third_sticky7f88",
]
_B3_C = ["cvtsd2ss_zero", "cvtsd2ss_negzero"]
_B3_R = [
          "cvtsd2ss_tie/nearest", "cvtsd2ss_tie/down", "cvtsd2ss_tieodd/nearest", "cvtsd2ss_tieodd/down",
          "cvtsd2ss_sticky/down", "cvtsd2ss_third/down", "cvtsd2ss_maxtie/down", "cvtsd2ss_tinyinexact/up",
          "cvtsd2ss_tinyafter/nearest", "cvtsd2ss_tinyafter/up", "cvtsd2ss_halfmin/nearest", "cvtsd2ss_negden/zero",
          "cvtsd2ss_one", "cvtsd2ss_inf", "cvtsd2ss_neginf", "cvtsd2ss_qnan", "cvtsd2ss_snan",
          "cvtsd2ss_snan_payload", "cvtsd2ss_max", "cvtsd2ss_minnorm", "cvtsd2ss_minsub", "cvtsd2ss_exacttiny",
]
PINNED.update({n: _X for n in _B3_X})
PINNED.update({n: "x86isa cannot run it" for n in _B3_C})
PINNED.update({n: _R for n in _B3_R})

# B4's hardware reading lands before its batch, as B3's did (D272): its rows are PENDING until the batch names its
# pins, so the tracked block stays byte-identical. B3 (D273) retired the set its own rows sat in.
PENDING = {"p_cvtsi2ss", "p_cvtsi2ssq", "p_cvtsi2sdq"}

COMIS = {"p_comisd": ("true", ".q"), "p_ucomisd": ("false", ".q"),
         "p_comiss": ("true", ".d"), "p_ucomiss": ("false", ".d")}


def rows():
    M.ROWS.clear()
    M.build()
    built = {r[0] for r in M.ROWS}
    missing = sorted(set(PINNED) - built)
    if missing:
        raise SystemExit("mk_anchors: PINNED names rows mk_rows.py does not build: %s" % missing)
    return list(M.ROWS)


def hx(v, digits):
    return "0x%0*x" % (digits, v)


# (theorem, which hwprobe rows, the tuple type, how a row prints, the per-row check)
FAMILIES = [
    ("b0_comis_pins", lambda fn: fn in COMIS,
     "Bool × Size × BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (COMIS[fn][0], COMIS[fn][1], hx(mx, 4), hx(a, 16), hx(b, 16),
                                           hx(want, 3), hx(fl, 2)),
     ["(fun (o, sz, mx, a, b, e, fl) =>",
      "  let t := step ⟨.vcomis o sz .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl (b0Rflags t.flags &&& 0x8d5) e)"]),
    ("b0_minmax_pins", lambda fn: fn in ("p_minsd", "p_minss"),
     "Size × BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (".q" if fn == "p_minsd" else ".d", hx(mx, 4), hx(a, 16),
                                           hx(b, 16), hx(want, 16), hx(mask, 16), hx(fl, 2)),
     ["(fun (sz, mx, a, b, r, m, fl) =>",
      "  let t := step ⟨.vminmax false sz .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& m) r)"]),
    ("b0_cvtss2sd_pins", lambda fn: fn == "p_cvtss2sd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtss2sd .x1 .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
    ("b0_cvtsi2sd_pins", lambda fn: fn == "p_cvtsi2sd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtsi2 true false .x0 .rdi, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b0_cvttsd2si_pins", lambda fn: fn == "p_cvttsd2si",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, r, fl) =>",
      "  let t := step ⟨.vcvtt2si true false .rax .x0, 4⟩ (b0Pre mx a 0)",
      "  b0Agrees t mx fl (t.regs.rax &&& 0xffffffff) r)"]),
    ("b1_mulsd_pins", lambda fn: fn == "p_mulsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .mul .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b1_mulss_pins", lambda fn: fn == "p_mulss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .mul .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_addsd_pins", lambda fn: fn == "p_addsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .add .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_subsd_pins", lambda fn: fn == "p_subsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .sub .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_divsd_pins", lambda fn: fn == "p_divsd",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .div .q .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64) r)"]),
    ("b2_addss_pins", lambda fn: fn == "p_addss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .add .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_subss_pins", lambda fn: fn == "p_subss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .sub .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    ("b2_divss_pins", lambda fn: fn == "p_divss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.varith .div .d .x0 .x1, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x0).setWidth 64 &&& 0xffffffff) r)"]),
    # B3: the probe's own shape, `cvtsd2ss %xmm0, %xmm1` with a canary in xmm1's bits 63:32, all 64 bits checked
    ("b3_cvtsd2ss_pins", lambda fn: fn == "p_cvtsd2ss",
     "BitVec 32 × BitVec 64 × BitVec 64 × BitVec 64 × BitVec 32",
     lambda fn, mx, a, b, want, mask, fl: (hx(mx, 4), hx(a, 16), hx(b, 16), hx(want, 16), hx(fl, 2)),
     ["(fun (mx, a, b, r, fl) =>",
      "  let t := step ⟨.vcvtsd2ss .x1 .x0, 4⟩ (b0Pre mx a b)",
      "  b0Agrees t mx fl ((t.getXmm .x1).setWidth 64) r)"]),
]


def block():
    rs = rows()
    lines = [BEGIN]
    used = 0
    for thm, pick, ty, fmt, check in FAMILIES:
        allf = [r for r in rs if pick(r[1])]
        used += len(allf)
        fam = [r for r in allf if r[0] in PINNED]
        lines += ["", "theorem %s :" % thm, "  ([  -- %d of hwprobe's %d rows" % (len(fam), len(allf))]
        for i, (n, fn, mx, a, b, want, mask, fl) in enumerate(fam):
            sep = "," if i + 1 < len(fam) else ""
            lines.append("    (%s)%s  -- %s · %s" % (", ".join(fmt(fn, mx, a, b, want, mask, fl)), sep, n,
                                                   PINNED[n]))
        lines.append("  ] : List (%s)).all" % ty)
        lines += ["    " + c for c in check]
        lines[-1] += " = true := by decide"
    pending = sum(1 for r in rs if r[1] in PENDING)
    if used + pending != len(rs):
        raise SystemExit("mk_anchors: %d of mk_rows.py's rows are in no family and not pending"
                         % (len(rs) - used - pending))
    lines += ["", END]
    return lines


def extract(text):
    """The tracked block, or None when either marker is missing."""
    ls = text.split("\n")
    if BEGIN not in ls or END not in ls:
        return None
    i, j = ls.index(BEGIN), ls.index(END)
    return ls[i:j + 1] if i < j else None


def compare(text, want):
    got = extract(text)
    if got is None:
        return ["the generated block's markers are missing from Tests/Anchors.lean"]
    if got == want:
        return []
    bad = [k for k in range(max(len(got), len(want)))
           if k >= len(got) or k >= len(want) or got[k] != want[k]]
    return ["%d line(s) differ from the generator, first at block line %d" % (len(bad), bad[0])]


def selftest():
    want = block()
    text = open(ANCHORS, encoding="utf-8").read()
    row = next(l for l in want if "cvtsi2sd_zero/down " in l)
    arms = [
        ("control: the tracked block is the generator's output", not compare(text, want)),
        ("a row's expected value is changed",
         bool(compare(text.replace(row, row.replace(", 0x0000000000000000, 0x00)", ", 0x8000000000000000, 0x00)")), want))),
        ("a row is dropped", bool(compare(text.replace(row + "\n", ""), want))),
        ("the END marker is lost", bool(compare(text.replace(END, "  --"), want))),
    ]
    ok = True
    for name, good in arms:
        print(("  ✔ " if good else "  ✖ ") + name)
        ok = ok and good
    print("✅ mk_anchors selftest" if ok else "⛔ mk_anchors selftest FAILED")
    return 0 if ok else 1


def main(argv):
    if "--selftest" in argv:
        return selftest()
    if "--check" in argv:
        bad = compare(open(ANCHORS, encoding="utf-8").read(), block())
        for b in bad:
            print("⛔ " + b)
        if not bad:
            print("✅ Tests/Anchors.lean carries mk_anchors.py's block byte for byte (%d lines)" % len(block()))
        return 1 if bad else 0
    unknown = [a for a in argv if a.startswith("--")]
    if unknown:
        print("mk_anchors: unknown flag(s) %s" % unknown)
        return 2
    print("\n".join(block()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
