#!/usr/bin/env python3
"""THE README'S HEADLINE NUMBERS, GATED.

WHY THIS EXISTS.  `README.md` is the first thing a reader of this repository
sees, and it carried a snapshot paragraph — forms covered, batches landed,
vectors, pre-states, cases — that NOTHING read.

⛔ P1 BATCH 16 FOUND IT FOUR BATCHES STALE: "twelve batches landed",
"388 of the 525 forms", "527 vectors · 80 pre-states · 42160 cases", against a
model at 16 batches, 429 forms and 627 vectors.  Batches 13, 14 and 15 each
updated `Main.lean`'s literal, regenerated `docs/COVERAGE.md`, and wrote a
differential record — and left this paragraph alone, because no gate read it.

⇒ 🔑 AND THE PARAGRAPH BENEATH IT IS WHY IT SURVIVED.  It said the figures were
"a snapshot" and that the generated file "is the claim".  That disclaimer did
not make the numbers harmless; it made them UNREADABLE AS WRONG.  A reader who
is told not to trust a number does not check it.  **A disclaimer is not a gate**
— it converts a false claim into an expected one, which is worse than an
unqualified false claim, because an unqualified one still looks wrong to
somebody.  D41's rule (`check_coverage_prose.py`) arriving in a third document,
this time wearing a warning label that read as diligence.

THE ANCHORS, AND WHY THEY CANNOT DRIFT IN STEP.  Nothing here is checked against
another hand-written sentence:

  * forms covered, vectors, mnemonics  <- `docs/COVERAGE.md`, GENERATED by
    `lake exe x86lean-diff coverage` and itself gated by CI for staleness;
  * batches landed  <- the COUNT of `docs/DIFFERENTIAL-P<p>-BATCH<n>.md` files,
    one per batch, PER PHASE, the same anchor `check_coverage_prose.py` uses;
  * pre-states and cases  <- the fenced result block of the LAST record in
    (phase, batch) order, written when that batch's run was made.

⭐⭐ P2 ITEM 1 (BATCH 22) WIDENED THE ANCHOR FROM `P1` TO `P<p>`, AND THAT IS THE
HALF OF THE BATCH THIS FILE EXISTS FOR.  Every glob here read
`DIFFERENTIAL-P1-BATCH*.md` literally.  The first P2 record would therefore have
been INVISIBLE to both gates: the README's `cases` and `pre-states` would have
gone on being checked against P1 batch 21's run for ever, and the prose gate
would have reported "CLEAN — all 21 P1 batches" while naming none of P2.
⇒ A GATE WHOSE SUBJECT IS NAMED BY A LITERAL STOPS SEEING THE WORK THE MOMENT
THE WORK IS RENAMED, and it reports agreement rather than silence
([[unobserved-regions-report-agreement]]).  Widening it was not optional
housekeeping; without it this batch could not have been gated at all.

WHAT THIS DOES NOT CHECK: that the surrounding English is true.  It checks the
NUMBERS, which are the part that goes stale silently.  The limit is stated
rather than left for a reader to find.
"""
import os, re, sys, glob, subprocess, shutil, tempfile

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)


def selftest():
    """⭐ THE POSITIVE CONTROL, AND IT MUTATES EVERY NUMBER THIS GATE READS.

    ⛔ D45 IS WHY IT IS SHAPED THIS WAY.  Batch 15's window gate was checked by
    two mutations that both happened to land in the FIRST of the two windows it
    parsed, so its selftest passed while it read only half its subject.  A gate
    with six claims and three sources needs a mutation per claim, not a mutation
    per gate — and one on a SOURCE as well, because a gate that parsed the
    README and compared it to itself would pass every README-side mutation and
    still be checking nothing.
    """
    files = ["README.md", "docs/COVERAGE.md", _records()[-1][2]]
    saved = {f: open(f).read() for f in files}
    # (label, file, from, to) — one per claim, then one on a source
    muts = [
        ("P1 batches landed", "README.md", "P1 SEALED — ", "P1 SEALED — 9"),
        ("P2 batches landed", "README.md", "P2 IN PROGRESS — ", "P2 IN PROGRESS — 9"),
        ("forms covered",   "README.md", "** of the 525 rows**", "**7 of the 525 rows**"),
        ("roster total",    "README.md", " of the 525 rows**", " of the 524 rows**"),
        ("vectors",         "README.md", " vectors · ", "1 vectors · "),
        ("pre-states",      "README.md", " pre-states · ", "1 pre-states · "),
        ("cases",           "README.md", " cases · 0 unexplained", "1 cases · 0 unexplained"),
        ("SOURCE: coverage table", "docs/COVERAGE.md",
         "differentially tested forms", "differentially tested forms "),
    ]
    ok = True
    try:
        for label, f, a, b in muts:
            body = saved[f]
            if label == "P1 batches landed":
                body = re.sub(r'(\*\*P1 SEALED — )(\d+)( batches landed)',
                              r'\g<1>99\g<3>', body, count=1)
            elif label == "P2 batches landed":
                body = re.sub(r'(P2 IN PROGRESS — )(\d+)( batch)',
                              r'\g<1>99\g<3>', body, count=1)
            elif label == "forms covered":
                body = re.sub(r'\*\*(\d+)( of the \d+ rows\*\* in \[`p1/roster)',
                              r'**7\g<2>', body, count=1)
            elif label == "roster total":
                body = re.sub(r'(\*\*\d+ of the )(\d+)( rows\*\* in \[`p1/roster)',
                              r'\g<1>524\g<3>', body, count=1)
            elif label == "vectors":
                body = re.sub(r'(\d+)( vectors · \d+ pre-states)', r'1\g<2>', body, count=1)
            elif label == "pre-states":
                body = re.sub(r'(vectors · )(\d+)( pre-states)', r'\g<1>1\g<3>', body, count=1)
            elif label == "cases":
                body = re.sub(r'(pre-states · )(\d+)( cases)', r'\g<1>1\g<3>', body, count=1)
            else:
                # mutate the GENERATED side instead: the gate must notice.
                body = re.sub(r'(covering \*\*)(\d+)', r'\g<1>1', body, count=1)
            if body == saved[f]:
                print(f"  ✖ {label}: the mutation changed NOTHING — the control "
                      f"never created its condition, so this arm proves nothing")
                ok = False
                continue
            open(f, "w").write(body)
            r = subprocess.run([sys.executable, __file__], capture_output=True, text=True)
            open(f, "w").write(saved[f])
            if r.returncode == 0:
                print(f"  ✖ {label}: MUTATED AND THE GATE STAYED GREEN")
                ok = False
            else:
                print(f"  ✔ {label}: caught (rc {r.returncode})")
    finally:
        for f, body in saved.items():
            open(f, "w").write(body)
    # and the missing-subject path: a gate that cannot find its subject must
    # FAIL, not pass.  (D45's other half: silence is not agreement.)
    saved_r = open("README.md").read()
    try:
        open("README.md", "w").write(re.sub(
            r'\*\*P1 SEALED.*?0 oracle leaks\n```', '', saved_r,
            count=1, flags=re.S))
        r = subprocess.run([sys.executable, __file__], capture_output=True, text=True)
        if r.returncode == 0:
            print("  ✖ paragraph DELETED and the gate stayed green"); ok = False
        else:
            print(f"  ✔ paragraph deleted: caught (rc {r.returncode})")
    finally:
        open("README.md", "w").write(saved_r)

    print("✅ check_readme_snapshot selftest: every claim and one source mutated, "
          "each caught" if ok else "⛔ check_readme_snapshot selftest FAILED")
    sys.exit(0 if ok else 1)


def _records():
    """Every differential record as (phase, batch, path), in run order."""
    out = []
    for f in glob.glob("docs/DIFFERENTIAL-P*-BATCH*.md"):
        m = re.search(r'DIFFERENTIAL-P(\d+)-BATCH(\d+)\.md$', f)
        if m:
            out.append((int(m.group(1)), int(m.group(2)), f))
    return sorted(out)


def _batch_numbers():
    return [b for (p, b, _) in _records() if p == 1]


if "--selftest" in sys.argv:
    selftest()

def die(msg, code=1):
    print(msg); sys.exit(code)

readme = open("README.md").read()
cov = open("docs/COVERAGE.md").read()

# ── the generated coverage line is the authority for three of the five ──────
m = re.search(r'Roster: (\d+) mnemonics in (\d+) differentially tested forms, '
              r'covering \*\*(\d+) of the (\d+) rows\*\*', cov)
if not m:
    die("⛔ could not parse the roster line of docs/COVERAGE.md. A missing "
        "subject is not a pass.", 2)
cov_mnem, cov_vecs, cov_forms, cov_total = (int(g) for g in m.groups())

recs = _records()
if not recs:
    die("⛔ no docs/DIFFERENTIAL-P<p>-BATCH<n>.md files found. A gate that cannot "
        "find its anchor reports a failure, not a pass.", 2)
n_p1 = max([b for (p, b, _) in recs if p == 1], default=0)
n_p2 = max([b for (p, b, _) in recs if p == 2], default=0)
latest_path = recs[-1][2]

latest = open(latest_path).read()
lm = re.search(r'cases=(\d+)', latest)
pm = re.search(r'(\d+) vectors · (\d+) pre-states', latest)
if not lm or not pm:
    die(f"⛔ could not find the result block in "
        f"{latest_path} (expected `cases=N` and "
        f"`N vectors · N pre-states`). A missing subject is not a pass.", 2)
rec_cases = int(lm.group(1))
rec_vecs, rec_pre = int(pm.group(1)), int(pm.group(2))

# ⚠️ The record and the generated table are two independent writes of the vector
# count.  Checking them against each other FIRST means the README is compared to
# a figure two artifacts already agree on.
if rec_vecs != cov_vecs:
    die(f"⛔ docs/COVERAGE.md says {cov_vecs} vectors and "
        f"{latest_path} says {rec_vecs}. The two "
        f"anchors disagree, so neither can be used to check the README.", 2)

# ── what the README claims ──────────────────────────────────────────────────
rm = re.search(r'\*\*P1 SEALED — (\d+) batches landed\. '
               r'P2 IN PROGRESS — (\d+) batch(?:es)? landed\.\*\*', readme)
fm = re.search(r'\*\*(\d+) of the (\d+) rows\*\* in \[`p1/roster\.tsv`\]', readme)
sm = re.search(r'(\d+) vectors · (\d+) pre-states · (\d+) cases', readme)
if not (rm and fm and sm):
    die("⛔ could not find the README snapshot paragraph (batches landed, "
        "`N of the M rows`, and the `N vectors · N pre-states · N cases` "
        "block). A missing subject is not a pass.", 2)

claims = {
    "P1 batches landed": (int(rm.group(1)), n_p1, "docs/DIFFERENTIAL-P1-BATCH<N>.md count"),
    "P2 batches landed": (int(rm.group(2)), n_p2, "docs/DIFFERENTIAL-P2-BATCH<N>.md count"),
    "forms covered":   (int(fm.group(1)), cov_forms,  "docs/COVERAGE.md"),
    "roster total":    (int(fm.group(2)), cov_total,  "docs/COVERAGE.md"),
    "vectors":         (int(sm.group(1)), cov_vecs,   "docs/COVERAGE.md"),
    "pre-states":      (int(sm.group(2)), rec_pre,    latest_path),
    "cases":           (int(sm.group(3)), rec_cases,  latest_path),
}

bad = [(k, got, want, src) for k, (got, want, src) in claims.items() if got != want]
if bad:
    print("⛔ README.md's snapshot paragraph is STALE:")
    for k, got, want, src in bad:
        print(f"     {k}: README says {got}, {src} says {want}")
    print("   Update the paragraph in README.md. It is the first thing a reader "
          "of this repository sees, and it was wrong for four batches before "
          "this gate existed.")
    sys.exit(1)

print(f"readme-snapshot gate: CLEAN — all {len(claims)} headline numbers agree "
      f"with the generated coverage table and the {len(recs)} differential records "
      f"({cov_forms}/{cov_total} forms, {cov_vecs} vectors, {rec_cases} cases)")
